// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmaKsueXt74JeaOerE4V-8vYpxursxXXA',
    appId: '1:1008052733284:web:d8731a4e209ac5f2782671',
    messagingSenderId: '1008052733284',
    projectId: 'reviewflow-31290',
    authDomain: 'reviewflow-31290.firebaseapp.com',
    storageBucket: 'reviewflow-31290.firebasestorage.app',
    measurementId: 'G-9FECEYM2VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX9MPvYBVA4Zw83Npe2nG6J20yYwiDXe4',
    appId: '1:1008052733284:android:ffd957d22981e58b782671',
    messagingSenderId: '1008052733284',
    projectId: 'reviewflow-31290',
    storageBucket: 'reviewflow-31290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85ZivmonAv73OMjz5F80KgG-l-0OJ6Mg',
    appId: '1:1008052733284:ios:f8525f64dcd990d1782671',
    messagingSenderId: '1008052733284',
    projectId: 'reviewflow-31290',
    storageBucket: 'reviewflow-31290.firebasestorage.app',
    iosBundleId: 'com.example.reviewflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC85ZivmonAv73OMjz5F80KgG-l-0OJ6Mg',
    appId: '1:1008052733284:ios:f8525f64dcd990d1782671',
    messagingSenderId: '1008052733284',
    projectId: 'reviewflow-31290',
    storageBucket: 'reviewflow-31290.firebasestorage.app',
    iosBundleId: 'com.example.reviewflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmaKsueXt74JeaOerE4V-8vYpxursxXXA',
    appId: '1:1008052733284:web:388eecabe96cab08782671',
    messagingSenderId: '1008052733284',
    projectId: 'reviewflow-31290',
    authDomain: 'reviewflow-31290.firebaseapp.com',
    storageBucket: 'reviewflow-31290.firebasestorage.app',
    measurementId: 'G-1SQ8ZVZSPE',
  );

}